### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by vinidiktov** [Flutterando/hasura_connect#64]
Does hasura_connect support the macOS target?

**Comment by Bwolfs2** [comment]
Working on it

**Comment by vinidiktov-edsd** [comment]
Any progress?

**Comment by Bwolfs2** [comment]
I guess is workin on the last version

**Comment by vinidiktov** [comment]
Why did you reopen it?

**Comment by Bwolfs2** [comment]
I forget to test on it, and how we are trying to fix all issues, this is one thing that i want to test =)

**Comment by ReniDelonzek** [comment]
Still not working in the latest version

`Unhandled Exception: ConnectionError: Websocket Error
#0      HasuraConnect._renewConnector.<anonymous closure> (package:hasura_connect/src/presenter/hasura_connect_base.dart:398:39)
#1      Left.fold (package:either_dart/src/either.dart:169:15)
#2      HasuraConnect._renewConnector (package:hasura_connect/src/presenter/hasura_connect_base.dart:398:27)
<asynchronous suspension>
#3      HasuraConnect._connect (package:hasura_connect/src/presenter/hasura_connect_base.dart:404:5)`
